### ISSUE TITLE
Negative unacked messages

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#759] opened 2017-09-13 20:56 UTC
We're experiencing a behavior were consumers have negative unackedMesasges count, huge backlogs, have availablePermits, are not blocked and yet are not receiving messages.
Consumer machines report that the have almost no messages in queue.
We're running 1.19-incubating.

This example is of topic `persistent://fury/global/948c07dd9c6a4c5faa106651d0d2cafd-account-movements/948c07dd9c6a4c5faa106651d0d2cafd-account-movements-partition-0`
```json
    "925c59c3045f4a39af9b34472623f73c-melipayments-receipts-movements" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 1219175,
      "blockedSubscriptionOnUnackedMsgs" : true,
      "unackedMessages" : 152277,
      "type" : "Shared",
      "msgRateExpired" : 0.0,
      "consumers" : [ {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-09c2ad7fd2a49d057-10.73.103.15",
        "availablePermits" : 91,
        "unackedMessages" : -49860,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.103.15:47300",
        "connectedSince" : "2017-08-30 20:44:19.126+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-0694bdfc5817f7af3-10.73.105.189",
        "availablePermits" : 87,
        "unackedMessages" : 118754,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.105.189:58453",
        "connectedSince" : "2017-08-30 20:44:20.118+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-04ea2b6ee82a2ade9-10.73.104.203",
        "availablePermits" : 98,
        "unackedMessages" : 58328,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.104.203:53460",
        "connectedSince" : "2017-08-30 20:44:28.898+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-09262b38b611871c9-10.73.103.239",
        "availablePermits" : 75,
        "unackedMessages" : -44463,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.103.239:45222",
        "connectedSince" : "2017-08-30 20:44:50.145+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-02cffb4d69393aa51-10.73.104.10",
        "availablePermits" : 85,
        "unackedMessages" : 73966,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.104.10:58965",
        "connectedSince" : "2017-08-30 20:44:54.732+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-0f4e04a029a239613-10.73.105.79",
        "availablePermits" : 65,
        "unackedMessages" : 2183,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.105.79:33272",
        "connectedSince" : "2017-09-12 17:26:25.868+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-046c50f69cb36846d-10.73.103.139",
        "availablePermits" : 56,
        "unackedMessages" : -443,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.103.139:43031",
        "connectedSince" : "2017-09-12 17:26:29.296+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-091165aafb986c96c-10.73.106.158",
        "availablePermits" : 90,
        "unackedMessages" : -3035,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.106.158:37738",
        "connectedSince" : "2017-09-12 17:26:39.390+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-074e75743c602e69f-10.73.104.223",
        "availablePermits" : 75,
        "unackedMessages" : 1837,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.104.223:60664",
        "connectedSince" : "2017-09-12 17:26:39.435+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-01137dae0559e78e8-10.73.106.241",
        "availablePermits" : 77,
        "unackedMessages" : -2551,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.106.241:40963",
        "connectedSince" : "2017-09-12 17:27:02.569+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-07f6a2096808b30c3-10.73.106.41",
        "availablePermits" : 99,
        "unackedMessages" : -2439,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.106.41:48132",
        "connectedSince" : "2017-09-12 17:27:16.081+0000",
        "clientVersion" : "1.19.0-incubating"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "i-0cc9c33a29333699e-10.73.106.181",
        "availablePermits" : 100,
        "unackedMessages" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "address" : "/10.73.106.181:60881",
        "connectedSince" : "2017-09-13 20:10:37.227+0000",
        "clientVersion" : "1.19.0-incubating"
      } ]
    }
```

Internal Stats for the partition shows:
```json
    "925c59c3045f4a39af9b34472623f73c-melipayments-receipts-movements" : {
      "markDeletePosition" : "7774731:289032",
      "readPosition" : "7774731:289033",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 26329750,
      "cursorLedger" : 7773772,
      "cursorLedgerLastEntry" : 14392,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2017-09-12 15:55:13.214+0000",
      "state" : "Open"
    }
```

Info Internal for the subscription shows:
```json
{
  "markDelete": {
    "entryId": 352016,
    "ledgerId": 7765017
  },
  "individualDeletedMessages": [
    {
      "to": {
        "entryId": 352027,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352017,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352038,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352028,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352049,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352039,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352060,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352050,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352068,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352061,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352071,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352069,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352079,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352072,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352082,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352080,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352090,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352083,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352093,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352091,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352101,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352094,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352104,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352102,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352112,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352105,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352115,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352113,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352123,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352116,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352126,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352124,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352134,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352127,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352138,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352135,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352146,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352139,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352149,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352147,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352157,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352150,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352160,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352158,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352168,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352161,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352171,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352169,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352175,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352172,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352179,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352176,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352182,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352180,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352186,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352183,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352190,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352187,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352193,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352191,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352197,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352194,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352202,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352198,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352205,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352203,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352209,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352206,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352213,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352210,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352216,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352214,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352220,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352217,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352224,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352221,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352227,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352225,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352231,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352228,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352235,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352232,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352238,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352236,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352242,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352239,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352246,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352243,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352249,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352247,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352253,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352250,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352257,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352254,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352260,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352258,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352264,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352261,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352268,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352265,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352272,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352269,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352276,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352273,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352280,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352277,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352283,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352281,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352288,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352284,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352292,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352289,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352295,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352293,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352299,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352296,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352303,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352300,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352306,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352304,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352311,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352307,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352315,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352312,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352319,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352316,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352323,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352320,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352327,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352324,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352330,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352328,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352334,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352331,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352338,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352335,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352341,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352339,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352345,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352342,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352349,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352346,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352355,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352350,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352359,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352356,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352365,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352360,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352369,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352366,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352372,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352370,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352376,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352373,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352380,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352377,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352383,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352381,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352387,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352384,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352391,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352388,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352394,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352392,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352398,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352395,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352402,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352399,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352405,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352403,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352409,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352406,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352413,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352410,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352416,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352414,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352420,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352417,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352424,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352421,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352427,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352425,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352431,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352428,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352435,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352432,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352438,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352436,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352442,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352439,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352446,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352443,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352449,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352447,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352453,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352450,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352457,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352454,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352460,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352458,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352464,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352461,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352468,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352465,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352471,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352469,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352475,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352472,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352479,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352476,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352482,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352480,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352486,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352483,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352490,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352487,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352494,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352492,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352498,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352495,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352502,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352499,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352505,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352503,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352509,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352506,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352513,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352510,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352516,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352514,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352520,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352517,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352524,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352521,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352528,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352525,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352532,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352529,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352536,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352533,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352539,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352537,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352543,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352540,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352547,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352544,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352550,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352548,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352554,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352551,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352558,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352555,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352561,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352559,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352566,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352563,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352570,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352567,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352573,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352571,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352577,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352574,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352581,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352578,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352584,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352582,
        "ledgerId": 7765017
      }
    },
    {
      "to": {
        "entryId": 352592,
        "ledgerId": 7765017
      },
      "from": {
        "entryId": 352590,
        "ledgerId": 7765017
      }
    }
  ],
  "cursorsLedgerId": 7773772,
  "version": 809,
  "modificationDate": "2017-09-12 15:55:13.224+0000",
  "creationDate": "2017-03-20 20:12:03.197+0000"
}
``` 

Other subscriptions on the same topic seems OK.
I'm uploading a heap dump of the broker holding the topic atm.

**Comment by jai1** [comment] 2017-09-13 21:14
We too had seen the same behavior once and but couldn't get to the root cause or reproduce the issue.

**Comment by merlimat** [comment] 2017-09-14 05:16
The interesting part is that some of the consumers do have a positive `unackedMessages` count, though they're still not receiving messages. 

Couple of questions: 
 * Have this problem happened multiple times or just one occourrence?
 * Does disconnecting/reconnecting a single consumer unblock that consumer?
 * Does disconnecting/reconnecting all the consumers "resolves" the issue?

**Comment by merlimat** [comment] 2017-09-14 05:17
Ok, the whole subscription being blocked is explained by: 

```
     "blockedSubscriptionOnUnackedMsgs" : true,
      "unackedMessages" : 152277,
```

The limit kicked in for the subscription.

**Comment by merlimat** [comment] 2017-09-14 05:23
> Info Internal for the subscription shows:

For this one you mean "the content of the cursor z-node"?

That would actually be outdated information (it's only kept as a safepoint backup, in case the ledger itself is not readable, and updated only during ledger rollovers). The info from the `stats-internal` is the accurate one: 

```
      "individuallyDeletedMessages" : "[]",
```

**Comment by merlimat** [comment] 2017-09-14 05:25
In any case, my suspicion is that the delivery got stopped because the few consumers that got many unacked messages and the negative counts might be a consequence of that. I'm not really sure, I'll check the code tomorrow to refresh the logic there.

**Comment by sschepens** [comment] 2017-09-14 13:16
> Have this problem happened multiple times or just one occourrence?

This has happened several times

> Does disconnecting/reconnecting a single consumer unblock that consumer?

Haven't tried disconnecting a single consumer, have tried introducing new consumers but won't work.

> Does disconnecting/reconnecting all the consumers "resolves" the issue?

I believe so, couldn't try that yesterday cause we had some other troubles.

> The limit kicked in for the subscription.

The strange thing is that we have `ackTimeout` of 30 seconds and that consumer had been for over a day mostly receiving no messages. I should be impossible for the consumer to be blocked for such a long time when after aproximately 30 seconds those messages should be redelivered.

> In any case, my suspicion is that the delivery got stopped because the few consumers that got many unacked messages and the negative counts might be a consequence of that. I'm not really sure, I'll check the code tomorrow to refresh the logic there.

Probably, don't really know why unacked messages has a negative count. What I can say is that we typically have LOTS of redeliveries. As before, even though some consumers received a lot o messages and got blocked, even if most messages were not acked, 30seconds later the consumer should unblock because it should ask for a redelivery.

**Comment by merlimat** [comment] 2017-09-15 00:10
> The strange thing is that we have ackTimeout of 30 seconds and that consumer had been for over a day mostly receiving no messages. I should be impossible for the consumer to be blocked for such a long time when after aproximately 30 seconds those messages should be redelivered.

Maybe it would be possible to reproduce in a test env by setting a very low ack-timeout (eg: 1 sec) and have the consumers to randomly exceed the threshold to excersise that code path.

**Comment by jai1** [comment] 2017-09-21 19:44
@sschepens - Have you enabled batching for the producers on this topic?

**Comment by sschepens** [comment] 2017-09-21 20:22
@jai1 nope, we're not using batches

**Comment by merlimat** [comment] 2017-09-24 16:33
I was able to reproduce the issue locally with a simple consumer. Settings the ack-timeout to 1sec and to ack with a random delay that can exceed the threshold. 

The negative `unackedMessages` counters shows up after few minutes.

```java
PulsarClient client = PulsarClient.create("pulsar://localhost:6650");
        ConsumerConfiguration conf = new ConsumerConfiguration();
        conf.setSubscriptionType(SubscriptionType.Shared);
        conf.setAckTimeout(1, TimeUnit.SECONDS);
        Consumer consumer = client.subscribe("persistent://sample/standalone/ns1/my-topic", "my-sub", conf);

        ScheduledExecutorService executor = Executors.newScheduledThreadPool(10);

        Random r = new Random();

        while (true) {
            Message msg = consumer.receive();
            int delayMs = r.nextInt(2000);
            executor.schedule(() -> {
                consumer.acknowledgeAsync(msg);
            }, delayMs, TimeUnit.MILLISECONDS);
        }
```

Still no idea of cause or possible fix.

**Comment by merlimat** [comment] 2017-09-25 19:56
Ok, I think I have a rough idea of what is happening. 

The issue is triggered when the ack-timeout is triggered, the message is re-sent to a different consumer and then the original consumer is acking the message. 

I think we're decreasing the unacked count even though the message was not in the set anymore for consumer 1. I'll get a fix shortly

**Comment by merlimat** [comment] 2017-09-26 05:17
@sschepens I'm not 100% sure about the consumer getting stuck. Definitely there was a bug in updating the unacked messages count when the redelivery is triggered and the ack comes delayed.

Please try it out when possible so that we can confirm.

**Comment by merlimat** [comment] 2017-10-02 21:07
Closing this one in 1.20. Please reopen if the secondary issue (the stalled delivery) persist.

**Closed by merlimat** 2017-10-02 21:07 UTC
Labels: type/bug
