### ISSUE TITLE
NoClassDefFoundError encountered when using Producer (Java API)

### ISSUE THREAD

**Issue by rstout610** [apache/incubator-pulsar#855] opened 2017-10-24 23:59 UTC
#### Expected behavior

I wrote a simple Scala program to publish a single message to a local standalone Pulsar cluster. I expected the message to be successfully sent. Here is the Scala program:

```
package main

import org.apache.pulsar.client.api._

object Main {
  val localClusterUrl = "pulsar://localhost:6650"
  val topicName = "persistent://sample/standalone/ns1/my-topic"

  def main(args: Array[String]): Unit = {
    val client = PulsarClient.create(localClusterUrl)
    val producer = client.createProducer(topicName)
    producer.send("message".getBytes)
    producer.close()
    client.close()
  }
}
```
And the build.sbt:
```
mainClass := Some("Main")

libraryDependencies ++= {
    Seq(
      "org.apache.pulsar" % "pulsar-client" % "1.20.0-incubating"
    )
}
```

#### Actual behavior

When I run the above program, the following error is output:
```
[error] (run-main-0) org.apache.pulsar.client.api.PulsarClientException: java.lang.NoClassDefFoundError: org/apache/pulsar/checksum/utils/Crc32cChecksum
org.apache.pulsar.client.api.PulsarClientException: java.lang.NoClassDefFoundError: org/apache/pulsar/checksum/utils/Crc32cChecksum
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:342)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:182)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:57)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:46)
	at main.Main$.main(main.scala:16)
	at main.Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.NoClassDefFoundError: org/apache/pulsar/checksum/utils/Crc32cChecksum
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:686)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:298)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:376)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:307)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:182)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:57)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:46)
	at main.Main$.main(main.scala:16)
	at main.Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.checksum.utils.Crc32cChecksum
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:686)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:298)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:376)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:307)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:182)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:57)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:46)
	at main.Main$.main(main.scala:16)
	at main.Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
This is unexpected. I would appreciate any ideas as to what the issue could be.

#### Steps to reproduce

Install sbt. Create a new directory/working space. Create build.sbt as shown above. Create src/main/scala/main.scala as shown above. Run "sbt". In the sbt prompt, execute "compile" and "run".

#### System configuration
"org.apache.pulsar" % "pulsar-client" % "1.20.0-incubating"
sbt 0.13.15
java 1.8.0_144
Scala 2.11.2

**Comment by merlimat** [comment] 2017-10-25 00:05
Hi @rstout610, I'm not familiar with sbt. Is it fetching all the dependencies from `pulsar-client`? 

Can you show the classpath is using?

Another option is to use the `shaded` jar for the pulsar client dependency. That will include all the required dependencies (also shaded to avoid conflicts). 
In next release, this shaded jar will be the default, in the meantime you can use the Maven classifier to use it. 

For example, change the dependency as: 

```
"org.apache.pulsar" % "pulsar-client" % "1.20.0-incubating" classifier "shaded"
```

**Comment by rstout610** [comment] 2017-10-25 00:11
Thanks @merlimat, the "shaded" classifier worked!

**Comment by estebangarcia** [comment] 2018-02-20 11:12
Sorry for reviving this old issue, but I had the same issue using Java+Gradle with the 1.21.0-incubating client and what fixed it for me was using the JAR instead of the NAR for the pulsar-checksum dependency.

**Comment by sijie** [comment] 2018-02-20 20:49
@estebangarcia 

yeah. I think gradle has different resolver on resolving NAR dependency than maven. you have to use jar than nar for pulsar-checksum dependency.

**Closed** 2018-08-01 16:14 UTC
Labels: component/build, triage/week-30, type/question

**Comment by otmanel31** [comment] 2019-08-30 14:26
hi i have the same issue in Nifi context. I'm able to connect to Pulsar broker via NIFI flow but when i try to publish my data, i got an exception for checksum dependency and more precisly:

> 2019-08-29 09:15:26,749 ERROR [Timer-Driven Process Thread-5] o.a.n.p.pulsar.pubsub.PublishPulsar PublishPulsar[id=de260534-016c-1000-5f3d-db6103ca25d8] Unable to publish message to Pulsar broker pulsar://localhost:6650: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:413)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:215)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:78)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:55)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:52)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.send(PublishPulsar.java:115)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.onTrigger(PublishPulsar.java:83)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:205)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:948)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:315)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:449)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:376)
	... 17 common frames omitted

>

**Comment by sijie** [comment] 2019-08-30 21:27
@otmanel31 how do you build your NIFI processor? what are the dependencies you are using?
